---
- hosts: all
  become: yes
  tasks:
  - name: install webserver(apache2) on ubuntu20 node
    apt:
     name: apache2
     state: present
    when_os_family: "debian"
  
  - name: start apache2 service
    service: 
      name: apache2
      state: started
    when_os_family: "debian" 
     
  - name: install webserver(httpd) on amazonlinux2 node
    yum: 
     name: webserver(httpd)
     state: present
    when_os_family: "redhat" 
    
  - name: start httpd service
    service: 
      name: httpd 
      state: started
    when_os_family: "redhat"  